services:
# FIXME: Launch backend and frontend with docker compose, and make sure they can communicate with each other (use environment variables for the API URL) 

  solr:
    image: solr:latest
    container_name: solr_nomologia
    ports:
      - "8983:8983"
    volumes:
      - ./solr/solr_data:/var/solr
    command:
      - solr-precreate
      - nomologia